# Generated by Django 5.1.1 on 2024-10-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='film_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
